# Information du site
site_name: "Histoire et généalogie des Lanteri"
site_description: "Histoire et généalogie des Lanteri"
site_author: "Gilles LANTERI"
site_url: "https://gilfr.github.io/genea/"

# Copyright
copyright: "Copyright &copy; 2000-2022 Gilles Lantéri"

# Configuration
theme:
  name: "material"
  palette:
    primary: yellow
    accent: pink
  icon:
    logo: material/family-tree
  features:
    # - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate
  language: fr

# Fichiers techniques
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.superfences
# #   - codehilite:
# #       guess_lang: false
# #   - footnotes
# #   - meta
# #   - pymdownx.betterem:
# #       smart_enable: all
# #   - pymdownx.caret
# #   - pymdownx.critic
# #   - pymdownx.details
# #   # - pymdownx.emoji.emojione # Payant
# #   - pymdownx.inlinehilite
# #   - pymdownx.magiclink
# #   - pymdownx.mark
# #   - pymdownx.progressbar
# #   - pymdownx.smartsymbols
# #   - pymdownx.superfences
# #   - pymdownx.tasklist:
# #       custom_checkbox: true
# #   - pymdownx.tilde
# #   - toc:
# #       permalink: true
