# Information du site
site_name: "Histoire et généalogie des Lanteri"
site_description: "Histoire et généalogie des Lanteri"
site_author: "Gilles LANTERI"
site_url: "https://gilfr.github.io/genea/"

# Copyright
copyright: "Copyright &copy; 2000-2022 Gilles Lantéri - Histoire et généalogie des Lanteri. Tous droits réservés. Reproduction interdite sans autorisation."

# Configuration
theme:
  name: "material"
  palette:
    - scheme: default
      primary: yellow
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    logo: material/family-tree
  features:
    # - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate
  language: fr

# Fichiers techniques
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js

# Plug-ins
plugins:
  - tags:
      tags_file: tags.md

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  #   - codehilite:
# #       guess_lang: false
# #   - footnotes
# #   - meta
# #   - pymdownx.betterem:
# #       smart_enable: all
# #   - pymdownx.caret
# #   - pymdownx.details
# #   # - pymdownx.emoji.emojione # Payant
# #   - pymdownx.magiclink
# #   - pymdownx.mark
# #   - pymdownx.progressbar
# #   - pymdownx.smartsymbols
# #   - pymdownx.superfences
# #   - pymdownx.tasklist:
# #       custom_checkbox: true
# #   - pymdownx.tilde
# #   - toc:
# #       permalink: true
